<!DOCTYPE html>

<html>
    
    <head>
        <meta charset="UTF-8">
        <meta description="Kareem Mohamed Arafa WebPage">
        <title>Kareem Mohamed Arafa</title>
        
        <style>
            .name
            {
                font-family: 'Source Sans Pro', sans-serif;
                font-weight: 200;
                text-align: center;
                font-size: 49px;
                margin: auto;
                padding-bottom: 7px;
                margin-bottom: 3px;
                color: #9A0089;
            }
            
            
            .info
            {
                font-family: Arial, Helvetica, sans-serif;
                text-align: center;
                color: #FFF;
                letter-spacing: 3px;
                word-spacing: 4px;
                font-size: 18px;
                background: #8E8CD8;
                width: 300px;
                margin: auto;
                margin-bottom: 3px;
            }
            
            .moreinfo
            {
                font-family: Tahoma, Geneva, sans-serif;
                text-align: center;
                color: #4A5459;
                font-size: 18px;
                border-left: 15px solid #881798;
            }
            
            .line2
            {
                border: 1px dashed #6B69D6
            }
        </style>
    </head>
    
    <body>
        <h1 class="name">Kareem Mohamed Arafa</h1>

        <p class="info">Info About Me:</p>
        <p class="moreinfo">I am 15 Years Old. I live in Fayoum. I am web developer <br> who want to be a famous one in the future.</p>
        <br>
        <hr class="line2">
        
    </body>
    
</html>
